name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout actions
        uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install vika
        run: |
          pwd
          cd autoRun/
          pwd
          pip install --upgrade vika
          pip list
          python weige.py
          ls -al
#      - name: Update paper list
#        run: |
#          cd autoRun/
