name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout actions
        uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install vika
        run: |
          echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
          echo $name
          cd autoRun/

          pip install --upgrade vika
          pip list

          ls -al
