name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout actions
        uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          VIKA_TOKEN: ${{ secrets.VIKA_TOKEN }} # GitHub 密钥 ACCESS_TOKEN 是在第二步Settings的Secrets中新增时定义的Name,要保持一致
      - name: install vika

        run: |
          cd autoRun/
          pip install vika
          python weige.py
